language: generic 
sudo: required
services:
    - docker
    
before_install:
    - docker build -t peterdbitc/another-docker-tutorial -f Dockerfile.dev .
    
script:
  - docker run -e CI=true peterdbitc/another-docker-tutorial npm run test
  
deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-tut"
    env: "DockerTut-env"
    bucket_name: "elasticbeanstalk-eu-west-2-585873853404"
    bucket_path: "docker-tut"
    on:
        branch: master
    access_key_id: $Access Key
    secret_access_key: $AWS Secret Key